[build]
  publish = "final_site" 
  functions = "netlify/functions" 

[context.homologacao]
  publish = "final_site"
  command = "echo 'Deploying Final Site for Homologacao'"

[[redirects]]
  from = "/api/respostas/*"
  to = "/.netlify/functions/proxy"
  status = 200